version: "3"

services:
    nginx:
        build:
            context: ./frontend
        container_name: frontend
        ports:
            - 80:80
        volumes:
            - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
        environment:
            - BACKEND_URL=http://127.0.0.1:8000
        depends_on:
            - backend
    backend:
        build:
            context: ./backend
        container_name: backend
